[package]
authors = ["Sean Bowe <ewillbefull@gmail.com>"]
description = "Implementation of the BLS12-381 pairing-friendly elliptic curve construction"
documentation = "https://docs.rs/bls12_381/"
homepage = "https://github.com/zkcrypto/bls12_381"
license = "MIT/Apache-2.0"
name = "bls12_381"
repository = "https://github.com/zkcrypto/bls12_381"
version = "0.1.1"
edition = "2018"

[package.metadata.docs.rs]
rustdoc-args = [ "--html-in-header", "katex-header.html" ]

[dependencies]
serde = {version = "1.0.106", optional = true}

[dev-dependencies]
criterion = "0.2.11"
bincode = "1.2.1"

[[bench]]
name = "groups"
harness = false
required-features = ["groups"]

[dependencies.subtle]
version = "2.2.1"
default-features = false

[features]
default = ["groups", "pairings", "alloc", "serial"]
groups = []
pairings = ["groups"]
alloc = []
nightly = ["subtle/nightly"]
serial = []

# GLV patents US7110538B2 and US7995752B2 expire in September 2020.
endo = []
